# Generated by Django 6.0.7 on 2026-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('video_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('format_quality', models.CharField(blank=True, max_length=50)),
                ('format_id', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
